### PR TITLE
Remove docs layout casuing duplicate socials

### PR DESCRIPTION
**Pull request by JarrodKane**
I think there was an extra layout file added into the docs route when the parent routes layout is doing what it needs to do already. 
This file looked to not be doing much but it was adding an extra row of socials for no reason above the already existing one.

I've just removed the file for now to remove the extra layer of socials.

I thought I would just create this PR while checking out this cool project because the fix is so quick.
Is there a contribution guide for this project?

### CODE REVIEW

**Comment by oneezy** [comment]
hey @JarrodKane ! thanks for your contribution and interest in the project!

I actually fixed this on my end along with a **ton** of other things so I'm going to hold off on merging this PR.

Still trying to fix a few items on this end before I release but here's a little preview of what's coming (hopefully later today)

## To do
- [x] create "main" app for all other apps to live on the same level 
- [x] fixed layouts / duplicate content 
- [x] created `$base` links so stand-alone app links will work
- [x] bumped histoire to `v0.11.7`
- [x] better tailwind.config content paths
- [ ] convert Histoire (svelte) to Histoire (sveltekit)
- [ ] fix `plop app` to work w/ new layout structure

---

## For Contributing,
If you have a feature or bug fix , best thing to do is create an issue so we can start a discussion around it and figure out the best plan

**Comment by oneezy** [comment]
just did a push @JarrodKane , let me know if that fixed things

**Comment by JarrodKane** [comment]
@oneezy That's great work, I'll keep following as I'm working with a similar tech stack for work, and my own private repos.
I'll create an issue from now on first, thanks for the feedback

**Comment by oneezy** [comment]
Thanks @JarrodKane ! Sounds like a plan. Gad it worked for you

**Pull request closed without merging**
